[package]
name = "urldecode"
version = "0.1.0"
authors = ["Luca Marcelli <luca@cerrato.ch>"]
edition = "2018"
description = "URL decoding made easy"
license = "MIT"
exclude = [
    ".idea/*",
    "*.iml",
]

[dependencies]
